# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Mileage
                                 A QGIS plugin
 plana
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-17
        copyright            : (C) 2024 by lanerchen
        email                : 1452052463@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'lanerchen'
__date__ = '2024-05-17'
__copyright__ = '(C) 2024 by lanerchen'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Mileage class from file Mileage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plana import MileagePlugin
    return MileagePlugin()
